name: Deploy PR Preview
on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write
  id-token: write

env:
  PROJECT_ID: showme-production
  SERVICE_ACCOUNT: firebase-adminsdk-fbsvc@showme-production.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/639849417444/locations/global/workloadIdentityPools/github-actions/providers/github

jobs:
  preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - run: npm ci
      - run: npm --prefix functions ci
      - run: npm run build:functions
      - run: npm run build:all

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ steps.auth.outputs.credentials_file_path }}
          projectId: ${{ env.PROJECT_ID }}
